### ISSUE TITLE
Combining all external refs into the same yaml specification

### ISSUE THREAD

**Issue by candysmurf** [APIDevTools/json-schema-ref-parser#106]
I tried to combine all external refs into the same yaml file. I used the following code.

```sh
$RefParser.bundle("/Users/xxx/Downloads/openapi/openapi.yaml")
    .then(function(schema) {
        console.log(schema);
  });
```
Output as

```sh
{
  components: {
    schemas: {
      RedfishError: [
        Object
      ]
    }
  },
  info: {
    contact: {
      name: 'DMTF',
      url: 'https://www.dmtf.org/standards/redfish'
    },
    description: 'This contains the definition of a Redfishservice.',
    title: 'Redfish API',
    version: '2018.2',
    'x-copyright': 'Copyright 2018 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright'
  },
  openapi: '3.0.1',
  paths: {
    '/redfish/v1/': {
      get: [
        Object
      ]
    },
    '/redfish/v1/AccountService': {
      get: [
        Object
      ],
      patch: [
        Object
      ],
      put: [
        Object
      ]
    },
    '/redfish/v1/AccountService/Accounts': {
      get: [
        Object
      ],
      post: [
        Object
      ]
    },
    '/redfish/v1/AccountService/Accounts/{ManagerAccountId}': {
      delete: [
        Object
      ],
      get: [
        Object
      ],
      patch: [
        Object
      ],
      put: [
        Object
      ]
    }.....
```
Why is all Object? Shouldn't the original content be kept?

**Comment by JamesMessinger** [comment]
The `console.log()` method outputs a "human friendly" representation of whatever you pass it.  It includes things like color-coding, special representations of certain data types, and truncating of the output at a certain depth.  That last behavior is what you're seeing.  Rather than displaying perhaps hundreds of lines of JSON, the `console.log()` method chooses to truncate the output by just printing the word "Object" instead of the actual object.

If you _really_ want to print the _entire_ JSON structure on screen, then you should use the `JSON.stringify()` method first, to convert the object to a JSON string.  That way, the `console.log()` method will simply print the string as-is, without trying to make it "human friendly".  Here's an example of how to do that...

```javascript
$RefParser.bundle("/Users/xxx/Downloads/openapi/openapi.yaml")
    .then(function(schema) {
        // Convert the schema to a JSON string
        let json = JSON.stringify(schema, null, 2);

        // Print the JSON string
        console.log(json);
    });
```

**Comment by candysmurf** [comment]
@JamesMessinger, your tool is awesome! thanks for your help!

**Comment by JamesMessinger** [comment]
Thanks!  Glad you found it useful.   Btw... if you're using this for OpenAPI files, then you might want to check out another project of mine, [Swagger CLI](https://github.com/APIDevTools/swagger-cli) which is a command-line tool that uses this library

**Comment by candysmurf** [comment]
@JamesMessinger, thanks for the info. I'll check out Swagger CLI. Yes. We're using it for a Huge OpenAPI spec which has over 900+ external files.
