### ISSUE TITLE
Feature Request: Reduce Bundle Size

### ISSUE THREAD

**Issue by mrin9** [APIDevTools/json-schema-ref-parser#117]
I am trying to use this over a slow network therefore is the request.
On inspecting the dependency map, I found that you are using `js-yaml`, which in-turn depends on `esprima.js` 

`esprima.js` is ecma-script parser, has a huge size and not needed under modern node or browser environment. 
Would you consider replace the `js-yaml` dependency with `yaml`  and generate a much smaller bundle?

**Comment by JamesMessinger** [comment]
I've actually been wanting to replace `js-yaml` for a while now, specifically because it's so big.  I just haven't had time to compare other YAML libraries and find one that is both 1) significantly smaller, and 2) still works (i.e. passes all the tests)

So, yes, if you'd like to give `yaml` a try and see if it works, then I'd be happy to accept a PR.  🙏

**Comment by mrin9** [comment]
I took a dig at it today, and tried two different yaml parser, with `yaml` I was able to pass 192 tests out of 211. Without changing any code. 


But interestingly I found that the minified code that is generated by    
using `yaml` is `238 kb`,  
using `js-yaml` it is around `181 kb`  

though I am not sure if the minified build includes `esprima.js` in it as its minified size itself is `133 kb`

For now I will close this issue, will check with some other parsers when I get some time and if I achieve something will contact you then

**Comment by JamesMessinger** [comment]
Thanks for taking the time to investigate this.  Those results are definitely somewhat surprising.
