### ISSUE TITLE
incompatible with angular >= 6.0.0

### ISSUE THREAD

**Issue by cdyue** [APIDevTools/json-schema-ref-parser#129]
# Subject of the issue
Because json-schema-ref-parser requires node http & https, it cannot be used in Angular applications that use angular-cli >= 6.0.0

See this comment from angular-cli:
angular/angular-cli#9827 (comment)

# Your environment
angular>= 6.0

# Expected behavior
I can use  json-schema-ref-parser in my app and ng serve does not fail

# Actual behavior
ng serve fails with
```
ERROR in ./node_modules/json-schema-ref-parser/lib/resolvers/http.js
Module not found: Error: Can't resolve 'http' in '/Users/web/container-web/node_modules/json-schema-ref-parser/lib/resolvers'
ERROR in ./node_modules/json-schema-ref-parser/lib/resolvers/http.js
Module not found: Error: Can't resolve 'https' in '/Users/web/container-web/node_modules/json-schema-ref-parser/lib/resolvers'
```

**Comment by JamesMessinger** [comment]
Good point.  I'd happily accept a PR that switched [the http resolver](https://github.com/APIDevTools/json-schema-ref-parser/blob/master/lib/resolvers/http.js) from `http` and `https` to a browser-compatible library such as [node-fetch](https://www.npmjs.com/package/node-fetch)

**Comment by Bakerburgh** [comment]
For anyone interested in a quick workaround for Angular, I made [this fork](https://github.com/Bakerburgh/json-schema-ref-parser) where I removed the HTTP(S) feature. 

I modified the README to include directions for publishing it to a local NPM repository via [Verdaccio](https://verdaccio.org/) and some other steps you need to take inside your Angular app. (See [this SO answer](https://verdaccio.org/)).

This fork **is not** a good starting point for a PR. It's just a hacky workaround for those that don't need to resolve HTTP(s) references.

**Comment by rlyttle** [comment]
I'm facing the same issue here.

@Bakerburgh I've tried your fork, but getting the following error - could you possibly provide a little guidance here? I've checked the project out and npm installed it into my own project from a local directory rather than via a local npm registry.

`ERROR in ../json-schema-ref-parser/lib/util/url.js
Module not found: Error: Can't resolve 'url' in '/Users/rr/git/testproj/json-schema-ref-parser/lib/util'
ℹ ｢wdm｣: Failed to compile.
`

**Comment by sarathsnair** [comment]
Hi,

I am also facing this issue. I am using Angular 8 and SwaggerParser is failing because of this. In my scenario, I can't use the hacky solution due to some constraints.

**Comment by fricci** [comment]
same here, I'm using Angular 9 and json-schema-ref-parse 9.0.1 but I get the same error.

**Comment by tmalatinszki** [comment]
Hi,

Same here... :( Are there any plans to fix this issue in the near future?

Regards,
Tamás

**Comment by laneschmidt** [comment]
still getting this while using angular 9, no fix that i can find

**Comment by philsturgeon** [comment]
Is there one of you people in here who would send a PR? This is a free tool, and people experiencing problems are often the best people to be solving those problems. Otherwise you're asking somebody to carve time out of their day to fix something that they don't need for their personal projects, or their day job, or anything else, other than helping folks out. 

People do like helping folks out, but there are lots of other folks wanting help with lots of other things, so... maybe somebody here could step up and take a go at the suggestion James made last year?

> Good point. I'd happily accept a PR that switched [the http resolver](https://github.com/APIDevTools/json-schema-ref-parser/blob/master/lib/resolvers/http.js) from `http` and `https` to a browser-compatible library such as [node-fetch](https://www.npmjs.com/package/node-fetch)

**Comment by KensingtonTech** [comment]
For those who don't require resolution of external references, it shouldn't be a requirement at all to load any http module, which causes needless bundle bloat.  It should be optional.

**Comment by johnzondr** [comment]
i got it working, add this to package.json & reinstall:

` "browser": {
    "http": false,
    "https": false
  }`

**Comment by philsturgeon** [comment]
If this still needs fixing please do send a PR, otherwise I am glad we have a workaround! :)
