### ISSUE TITLE
Keep $ref some how when bundle

### ISSUE THREAD

**Issue by wenerme** [APIDevTools/json-schema-ref-parser#173]
Because $ref offen mean type of something, when render views, need the ref type to select the component.

e.g.

__Address.json__
```json
{
  "type": "object",
  "properties": {
    "a": {
      "type": "string"
    }
  }
}
```

__User.json__

```json
{
  "type": "object",
  "properties": {
    "address": {
      "$ref":"Address.json"
    }
  }
}
```

If the bundled result is 

```json
{
  "type": "object",
  "properties": {
    "address": {
      "_ref": "Address.json",
      "type": "object",
      "properties": {
        "a": {
          "type": "string"
        }
      }
    }
  }
}

```

Then the frontend can use the `"_ref": "Address.json"`  to match the component more precisely.

**Comment by JamesMessinger** [comment]
There's already some existing discussion going on about this in [Issue #135](https://github.com/APIDevTools/swagger-parser/issues/135).  I think your solution could be acceptable, but I'd like to get some other opinions too

**Comment by maxtuzz** [comment]
Indeed this looks good to me. Though perhaps persisting `$ref` instead of `_ref` would be preferred?

+1

**Comment by philsturgeon** [comment]
Persisting $ref would confuse tools which know what a $ref is and want to do something about it. It could cause some infinite loops, or just errors from tools which warn you they don't know how to deal with a $ref - which is why you're dereferencing in the first place. 

@MikeRalphson has done a bit of this.

**Comment by MikeRalphson** [comment]
I simply allowed the caller to specify a property name for it to be copied to if they wanted `$ref` preservation.

**Comment by JamesMessinger** [comment]
I like @MikeRalphson's approach.  We could add an option, like say `dereference.$refRename` that defaults to `false`.  

Any falsy value = remove the $ref as it does currently.  

Any string value = rename the $ref to the specified value

**Comment by ftheomunhoz** [comment]
That would definitely work in our case (from [Issue #135](https://github.com/APIDevTools/swagger-parser/issues/135)) and wouldn't generate a breaking change.

**Comment by bcherny** [comment]
Author of [json-schema-to-typescript](https://github.com/bcherny/json-schema-to-typescript) here. We'd love this features, as it would unblock a handful of issues related to emitting more intelligent TypeScript types.

As specific example, consider the following JSON Schema:

```ts
{
  additionalProperties: false,
  definitions: {
    a: {type: 'string'},
    b: {type: 'number'}
  },
  properties: {
    c: {
      additionalItems: false,
      items: [{$ref: '#/definitions/a'}, {$ref: '#/definitions/b'}],
      type: 'array'
    }
  },
  title: 'X,
  type: 'object'
}
```

We'd like to emit the following TypeScript types for this schema:

```ts
type A = string
type B = number

type X = {
  c: [] | [A] | [A, B]
}
```

Today, we accomplish this by *always* emitting standalone type names (here, `A` and `B`) for tuple members. However, this isn't the right behavior; it would be nice to refine our heuristic, where we look for the presences of `$ref`s as a sign that a type is meant to be reused, and therefore, named (we already use `id`s and `title`s for this today).

To do that, we'd love a way to know what a schema's original `$ref` pointed to. Any key name is fine for us, though you might consider using a `Symbol` in order to avoid a backwards-incompatible change to this library, and to avoid colliding with existing keys.

As a side note: It's possible to infer something like this today (roughly: traverse over a dereferenced schema and its source schema at the same time, and annotate the dereferenced schema where you see a `$ref` in its source schema). But this is a hack that doesn't work when a source node is in another file, since `$RefParser.resolve(..).get(..)` returns a dereferenced schema, not a source schema.

Please let me known if this is not something you're interested in, and I'll go ahead and fork `json-schema-ref-parser` so we can patch it in for our use case.

**Comment by JamesMessinger** [comment]
@bcherny - Thanks for providing another example of why this feature would be useful.  If somebody would like to submit a PR, I'd be happy to review it.  

However, I've realized that it's not actually as easy as I [suggested previously](https://github.com/APIDevTools/json-schema-ref-parser/issues/173#issuecomment-634135463).  The problem with simply keeping the `$ref` property (or renaming it) is that the same object can be referenced in many different places, so _which_ `$ref` do you keep?

Instead, it seems like we may need to add an array property (probably with a Symbol to avoid breaking changes) that contains all the refs that pointed to a particular object.

**Comment by bcherny** [comment]
> The problem with simply keeping the $ref property (or renaming it) is that the same object can be referenced in many different places, so which $ref do you keep?

@JamesMessinger That's a great catch!

Thinking about it more, I wonder if a simpler and more general-purpose approach might be to avoid setting a property at all, and expose an `onDereference` hook instead.

One possible API:

```ts
const result = await $RefParser.dereference('schema.json', {
  onDereference(originalSourceSchema, dereferencedSchema, originalRefPath, absoluteRefPath) {
    // ...
  }
})
```

A consume might then use this API to build up a mapping:

```ts
const map = new Map

const result = await $RefParser.dereference('schema.json', {
  onDereference(originalSourceSchema, dereferencedSchema, originalRefPath, absoluteRefPath) {
    if (!map.has(dereferencedSchema)) {
      map.set(dereferencedSchema, new Set)
    }
    map.get(dereferencedSchema).add(originalRefPath)
  }
})
```

This approach has a few benefits over the `Symbol`-based approach:

- It's strictly backwards-compatible, while I can come up with some convoluted cases where the `Symbol`-based approach is not
- It more closely sticks to the JSON-Schema spec, and avoids having to monkey-patch in properties specific to json-schema-ref-parser (in practice, this would mostly affect consumers that use TypeScript)
- It supports use cases that the `Symbol`-based approach does not (say, also collecting the original `$ref`-containing schemas)

**Comment by JamesMessinger** [comment]
I like that idea @bcherny!  What does everyone else think?  Would this work for your use-case?

/cc @wenerme @maxtuzz @MikeRalphson @philsturgeon @ftheomunhoz

**Comment by MikeRalphson** [comment]
Personally, I've only ever needed to know where a `$ref` **used to be** and not what locations previously pointed into a `$ref`ed component, and although using a callback would be a little more work (maintaining and comparing to a list of locations as you traversed the dereferenced object, or decorating it yourself), it certainly has the flexibility to enable those use-cases.

**Comment by philsturgeon** [comment]
This callback approach would work for the "live mock server wants to watch all $ref files for changes so it can reload" use-case. We'd just look file all filepaths and strip of anchors and watch that set of files.

**Comment by philsturgeon** [comment]
All conversations about changing how $ref should work should be done over here https://github.com/json-schema-org/referencing then when its decided we can all make sure tools follow it.
