### ISSUE TITLE
TypeScript compilation error

### ISSUE THREAD

**Issue by monooso** [APIDevTools/json-schema-ref-parser#175]
TypeScript reports the following compilation error, due to [this line](https://github.com/APIDevTools/json-schema-ref-parser/blob/master/lib/index.d.ts#L1).

```
node_modules/@apidevtools/json-schema-ref-parser/lib/index.d.ts:1:76 - error TS2307: Cannot find module 'json-schema'.

1 import { JSONSchema4, JSONSchema4Type, JSONSchema6, JSONSchema6Type } from 'json-schema';
```

`@types/json-schema` is listed as [a development dependency](https://github.com/APIDevTools/json-schema-ref-parser/blob/master/package.json#L59), but isn't installed along with your package.

Explicitly installing `@types/json-schema` as a development dependency fixes the error.

Is this expected behaviour? I'm pretty new to TypeScript.

**Comment by JamesMessinger** [comment]
The way I see it (though I could be persuaded otherwise), type definitions should always be devDependendencies.  They're not needed at runtime, and they're not needed at all for anyone who isn't using TypeScript.  If you _are_ using TypeScript, then you are take a devDependency on the type packages that are needed to make TypeScript work, including types that are needed by third-party libs.

I'd be curious to hear what other people think about this.  I could certainly be persuaded to move types to dependencies, but I suspect that some folks (especially those who aren't using TypeScript) won't like that because it pollutes their runtime node_modules.

**Comment by monooso** [comment]
@JamesMessinger I completely understand your reasoning.

I'm curious as to why I haven't encountered this with other packages. Do you know if installing the types as a dev dependency from DefinitelyTyped automatically takes care of this?

**Comment by JamesMessinger** [comment]
Now that TypeScript is rapidly growing in popularity, I suspect this issue will come up more frequently and the community will (hopefully) agree on a standard approach or solution to the problem. 🤞

Installing the types as a dev dependency will solve the problem.  I do that in a few of my apps for some third-party libs.
