### ISSUE TITLE
Bundled schema and `$id`

### ISSUE THREAD

**Issue by paulwib** [APIDevTools/json-schema-ref-parser#97]
It seems that when bundling a schema `$id` attributes aren't considered which makes the output incompatible with other JSON Schema tools, for example:

`a.json`:

```json
{
  "$id": "https://schema.example.com/a.json",
  "b": {
    "$ref": "b.json"
  }
}
```

`b.json`:

```json
{
  "$id": "https://schema.example.com/b.json",
  "properties": {
    "bar": {
      "$ref": "#/definitions/thing"
    }
  },
  "definitions": {
    "thing": {
      "type": "string"
    }
  }
}
```

Some code:

```javascript
const RefParse = require('json-schema-ref-parser');

RefParse.bundle('a.json')
  .then(s => {
    console.log(JSON.stringify(s, null, 2));
  });
```

Outputs:

```json
{
  "$id": "https://schema.example.com/a.json",
  "b": {
    "$id": "https://schema.example.com/b.json",
    "properties": {
      "bar": {
        "$ref": "#/b/definitions/thing"
      }
    },
    "definitions": {
      "thing": {
        "type": "string"
      }
    }
  }
}
```

The issue is that in JSON Schema `b.properties.bar.$ref` is resolved against the nested `b.$id` giving `https://schema.example.com/b.json#/b/definitions/bar` which doesn't actually exist.

This breaks other tools, like trying to use the bundled schema in [Ajv](https://github.com/epoberezkin/ajv).

I saw the [comment](https://github.com/BigstickCarpet/json-schema-ref-parser/issues/22#issuecomment-231783185) on #22 that the aims of this library do *not* include supporting JSON Schema and the `$id` keyword, but it's confusing as the first line of the README says: "Parse, Resolve, and Dereference *JSON Schema* $ref pointers" 😄  Latest JSON Schema has it's [own definition](http://json-schema.org/latest/json-schema-core.html#rfc.section.8.3) of `$ref` and no longer uses the expired [JSON Reference spec](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03) 😮 

Any chance of an option to consider `$id` when bundling?

**Comment by BigstickCarpet** [comment]
Hi @paulwib - Thanks for opening this issue.  As you pointed out, [I've said before](https://github.com/BigstickCarpet/json-schema-ref-parser/issues/22#issuecomment-231783185) that this library is an implementation of the JSON Reference specification and the JSON Pointer specification, **not** the JSON Schema specification. Thus, the id keyword isn't supported, because that's not part of JSON Reference or JSON Pointer.

That said... the name of this library is (perhaps inappropriately) **json-schema**-ref-parser, so it's easy to see why many people have been confused by its lack of support for the JSON Schema spec.  So, yeah, I will probably end up adding support for `id` and `$id` at some point, to eliminate the confusion and because multiple people have now requested it.  

No promises on timeframe though.  I have lots of other obligations competing for my time and attention, and this change is likely to be pretty complicated and require a lot of thought and thorough testing.

**Comment by BigstickCarpet** [comment]
Linking #22 and #95 here, for future reference

**Comment by philsturgeon** [comment]
Also related to #145.

**Comment by philsturgeon** [comment]
Let's leave #145 to handle this topic.
